replicaCount: 3

image:
  repository: my-reports-app
  tag: "1.0"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: my-reports.prod.local
      paths:
        - path: /
          pathType: Prefix


serviceAccount:
  create: true
  name: my-reports-sa-prod          

pdb:
  enabled: true
  minAvailable: 2