replicaCount: 2

image:
  repository: 118984406529.dkr.ecr.us-east-2.amazonaws.com/dev/my-reports-app
  tag: dev
  pullPolicy: Always


imagePullSecrets:
  - name: ecr-regcred


service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: my-reports.dev.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: true
  name: my-reports-dev

envSecrets:
  name: my-reports-db-secret

secret:
  name: my-reports-secrets
  data:
    DB_HOST: dev-db2.c78um84ewxvo.ap-south-1.rds.amazonaws.com
    DB_USER: readonly_dev
    DB_PASSWORD: OWiC1BMwQAjquNoRhJKD
    DB_NAME: ourshopee



